### PR TITLE
Fix Job Settings Page Break on Firefox

### LINKED ISSUE #10332: Job Settings Page Break
##### ISSUE TYPE
 - Bug Report

##### SUMMARY 
Note the Job Settings section label is not directly above the Job Settings link 
Screen Shot 2021-06-02 at 9 13 57 AM

##### ENVIRONMENT
* AWX version: 19.1
* AWX install method: docker for mac
* Ansible version:  
* Operating System: Mojave
* Web Browser: Firefox

##### STEPS TO REPRODUCE

See screenshot above

### PR DESCRIPTION
**Pull request by nixocio**
Fix Job Settings Page Break on Firefox

Closes: https://github.com/ansible/awx/issues/10332

Firefox:

image

Chrome: 

image

### CODE REVIEW

**Comment by nixocio** [comment]
recheck

File: awx/ui_next/src/screens/Setting/SettingList.jsx [hunk 1]
```diff
@@ -25,10 +25,11 @@ const SplitLayout = styled(PageSection)`
   }
 `;
 const Card = styled(_Card)`
-  display: inline-block;
-  break-inside: avoid;
-  margin-bottom: 24px;
-  width: 100%;
+  && {
```
Comment (marshmalien) [inline awx/ui_next/src/screens/Setting/SettingList.jsx:28]: Nice. I didn't realize that PatternFly's card styles were overriding our display property. 🔥

**Review by marshmalien — APPROVED** [review]

**Review by tiagodread — APPROVED** [review]
