### PR TITLE
Fix search toolbar clear all filters

### LINKED ISSUE #8474: Clear All Filters in Search should disappear
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After searching it is expected that Clear all filters should be removed after clearing all of the search chips.  

##### ENVIRONMENT
* AWX version: 14.1
* AWX install method:  docker for mac
* Ansible version:  2.9.13
* Operating System: Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1) Go to a list
2) Search for something on that list that generates 1 chip.
3) Notice that a chip is generated under the search input
4) Click on that chip (all chips) to remove it.

##### EXPECTED RESULTS
the chip is removed and `Clear all filters` is also removed
##### ACTUAL RESULTS

The chip is removed but `Clear all filters` is not removed. 

##### ADDITIONAL INFORMATION
weird filter

### PR DESCRIPTION
**Pull request by marshmalien**
### SUMMARY

Issue: https://github.com/ansible/awx/issues/8474

Dynamically removing the ToolbarFilter component threw the Toolbar component’s inner `filterInfo` state out of sync. The filters were responsible for notifying the Toolbar’s context of changes, so by removing them prematurely, the Toolbar was unaware that it needed to remove filters from its state. This PR persists the ToolbarFilter components, which allows the Toolbar to manage showing and hiding the filter list. 

filter

### ISSUE TYPE

- Bugfix Pull Request

### COMPONENT NAME

- UI

### CODE REVIEW

File: awx/ui/src/components/Search/Search.js [hunk 1]
```diff
@@ -65,6 +65,26 @@ function Search({
...
+    params.ansible_facts = params.host_filter.substring(
+      'ansible_facts__'.length
+    );
+    delete params.host_filter;
+  }
+
+  const searchChips = getChipsByKey(params, columns, qsConfig);
+  const [chipsByKey, setChipsByKey] = useState(
+    JSON.parse(JSON.stringify(searchChips))
+  );
```
Comment (AlexSCorey) [inline awx/ui/src/components/Search/Search.js:79]:
```suggestion
  const [chipsByKey, setChipsByKey] = useState(
getChipsByKey(params, columns, qsConfig)
  );
```

File: awx/ui/src/components/Search/Search.js [hunk 2]
```diff
@@ -65,6 +65,26 @@ function Search({
...
+
+  useEffect(() => {
+    Object.keys(chipsByKey).forEach((el) => {
+      chipsByKey[el].chips = [];
+    });
+    setChipsByKey({ ...chipsByKey, ...searchChips });
+  }, [location.search, searchChips.length]); // eslint-disable-line react-hooks/exhaustive-deps
```
Comment (AlexSCorey) [inline awx/ui/src/components/Search/Search.js]:
```suggestion
  useEffect(() => {
    Object.keys(chipsByKey).forEach((el) => {
      chipsByKey[el].chips = [];
    });
    setChipsByKey(getChipsByKey(params, columns, qsConfig));
  }, [location.search]);
```

searchChips is an object so it looks like searchChips.length is always going to be undefined.  if we can remove that dependency from the array then I think we can also remove the commented `eslint-disable-line...`

Finally, since we want to keep chipsByKey in sync with searchChips lets just use the getChipsByKey function to give us those values here.

**Review by AlexSCorey — CHANGES_REQUESTED** [review]
I did a cursory look at this and found some things that we could improve on.  If there are cases where my requested changes wouldn't work, like were searchChips is an array and not an object, then I'm good with the code as is.

File: awx/ui/src/components/Search/Search.js (hunk 2 above)
Comment (marshmalien) [reply awx/ui/src/components/Search/Search.js]: I agree that `searchChips.length` is unnecessary here and should be removed from the dependency array since it is a js object. 

```
const [chipsByKey, setChipsByKey] = useState(
    JSON.parse(JSON.stringify(searchChips))
);
 ````
Initializing the `chipsByKey` state (above) is key to removing any object reference to `searchChips` and to persisting the original filters. The goal of this PR was to build up the list of filters and maintain them even after the params change. When the user deletes a filter, instead of removing it from the `chipsByKey` object, we pass that specific filter's chips property an empty array. Keeping the original filter key around for PatternFly's Toolbar component was the trick to fixing the bug. 

```
setChipsByKey(getChipsByKey(params, columns, qsConfig));
```
The line above would overwrite the list of filters and bring back the original bug. 

```
setChipsByKey({ ...chipsByKey, ...searchChips });
```
By spreading the original `chipsByKey` and the current `searchChips` into the setter, I'm able to update the state with new search filters from `searchChips` while preserving the older search filter keys.

**Review by AlexSCorey — APPROVED** [review]
We talked offline.  We are going to make patternfly aware of their toolbar dynamic filtering of the toolbar.  This code works well for us.  Good work!

**Review by akus062381 — APPROVED** [review]
