### PR TITLE
Adds fix to allow look up to fetch data

### LINKED ISSUE #7935: Credential Look up won't fetch data
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Credential Look Up won't fetch data.
##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Load a form that has a credential look up
##### EXPECTED RESULTS

That I don't see:
Screen Shot 2020-08-19 at 11 22 36 AM

##### ACTUAL RESULTS

That I see:
Screen Shot 2020-08-19 at 11 22 36 AM

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
Fixes https://github.com/ansible/awx/issues/7935

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
Fixes:
Screen Shot 2020-08-19 at 11 22 36 AM

### CODE REVIEW

File: awx/ui_next/src/components/Lookup/CredentialLookup.jsx [hunk 1]
```diff
@@ -68,8 +68,8 @@ function CredentialLookup({
           actionsResponse?.data?.related_search_fields || []
         ).map(val => val.slice(0, -8)),
         searchableKeys: Object.keys(
-          actionsResponse.data.actions?.GET || {}
-        ).filter(key => actionsResponse.data.actions?.GET[key].filterable),
+          actionsResponse.data?.actions?.GET || {}
+        ).filter(key => actionsResponse.data?.actions?.GET[key].filterable),
```
Comment (jakemcdermott) [inline awx/ui_next/src/components/Lookup/CredentialLookup.jsx]: ``
```suggestion
        ).filter(key => actionsResponse.data?.actions?.GET[key]?.filterable),
```

**Review by jakemcdermott — APPROVED** [review]

**Comment by unlikelyzero** [comment]
@AlexSCorey taking this for a spin 🎪

**Comment by unlikelyzero** [comment]
tested. Executed the stubs manually and added another stub for our future coverage.
Found two other unrelated bugs:
https://github.com/ansible/awx/issues/7939
https://github.com/ansible/awx/issues/7938

**Review by unlikelyzero — APPROVED** [review]
