### PR TITLE
Modify handleDelete for JobTemplateDetails and WorkflowJobTemplateDetail

### LINKED ISSUE #6971: Raising warnings when deleting Workflow Job template using Details page
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Deletion of `Workflow Job Template` or `Job Template`  in details page is raising the following warning:

```text
react_devtools_backend.js:6 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in WorkflowJobTemplateDetail (created by I18n)
    in I18n (created by WithI18n)
    in WithI18n (created by WorkflowJobTemplate)
    in Route (created by WorkflowJobTemplate)
    in Switch (created by WorkflowJobTemplate)
    in article (created by Card)
    in Card (created by WorkflowJobTemplate)
    in section (created by PageSection)
    in PageSection (created by WorkflowJobTemplate)
    in WorkflowJobTemplate (created by Context.Consumer)
    in withRouter(WorkflowJobTemplate) (created by I18n)
    in I18n (created by WithI18n)
    in WithI18n (created by Context.Consumer)

```
##### STEPS TO REPRODUCE
Go to `Workflow Job Template` and delete a template. Look the console logs.

##### EXPECTED RESULTS
No warnings to be raised.

Possible solution:

https://github.com/ansible/awx/blob/602f2951b9fcecc668ee6d9d009b33eb9412dff1/awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx#L72

~~Replace the usage of the function above to helper function `useDeleteItems`.~~
This solution was not the ideal fit, since `useDeleteItems` should be used for `paginated` items.

Also applicable for Job Templates.

### PR DESCRIPTION
**Pull request by nixocio**
Update deletion of items for JobTemplateDetails and WorkflowJobTemplateDetail
to remove warnings related update on an unmounted component. Use custom
hook `useRequest`.

closes: #6971

### CODE REVIEW

File: awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx [hunk 1]
```diff
@@ -386,22 +388,22 @@ function JobTemplateDetail({ i18n, template }) {
             <DeleteButton
               name={name}
               modalTitle={i18n._(t`Delete Job Template`)}
-              onConfirm={handleDelete}
+              onConfirm={deleteJobTemplate}
             >
```
Comment (keithjgrant) [inline awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx:392]: perhaps instead of hiding the whole UI

File: awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx [hunk 2]
```diff
@@ -386,22 +388,22 @@ function JobTemplateDetail({ i18n, template }) {
             <DeleteButton
               name={name}
               modalTitle={i18n._(t`Delete Job Template`)}
-              onConfirm={handleDelete}
+              onConfirm={deleteJobTemplate}
```
Comment (keithjgrant) [inline awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx:391]: Perhaps instead of hiding the whole UI while the delete is loading (line 161), you could just disable this button temporarily. That way, if an error occurs, the screen doesn't disappear then reappear.

`<DeleteButton ... isDisabled={isLoading}>`

You may also need to update the DeleteButton to pass this prop through to the PF Button.

File: awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx [hunk 3]
```diff
@@ -82,16 +82,18 @@ function JobTemplateDetail({ i18n, template }) {
...
       history.push(`/templates`);
-    } catch (error) {
-      setDeletionError(error);
-    }
-    setHasContentLoading(false);
-  };
+    }, [templateId, history])
+  );
+
+  const { error, dismissError } = useDismissableError(deleteError);
```
Comment (keithjgrant) [inline awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx:96]: perfect!

File: awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx [hunk 4]
```diff
@@ -69,20 +67,22 @@ function WorkflowJobTemplateDetail({ template, i18n }) {
...
-    setHasContentLoading(false);
-  };
+    }, [id, history])
+  );
+
+  const { error, dismissError } = useDismissableError(deleteError);
+
+  if (isLoading) {
+    return <ContentLoading />;
+  }
```
Comment (keithjgrant) [inline awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx]: Same as JobTemplateDetail above: instead of rendering `<ContentLoading />`, keep the UI mounted & just disable the delete button while `isLoading` is true.

**Review by keithjgrant — COMMENTED** [review]
This looks good! I put a couple thoughts how to improve the UX a bit below, but this should fix the primary issue

File: awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx (hunk 4 above)
Comment (nixocio) [reply awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx]: Thanks for your review @keithjgrant, I will update per comments.

**Review by keithjgrant — APPROVED** [review]
