### PR TITLE
removing codemirror instantiation from $transition event

### LINKED ISSUE #569: Inventory variable changes not shown in UI until refresh
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 

##### ENVIRONMENT
* AWX version: 1.0.1.137
* AWX install method: docker on linux
* Ansible version:  2.4
* Operating System: Debian Strectch
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Didn't get it reproduced

##### EXPECTED RESULTS

I'm having a inventory defined in awx and when I want to update a variable the variable didn't get safed after all. Even if I remove the variables.

When I restart the Web Container it works again for a short time, in other words I can edit one variable and then I have to restart the container again. 

The `docker logs -f awx_web` don't provide any helpful information also I don't see any connection to the database in the logs of postgres.

### PR DESCRIPTION
**Pull request by jaredevantabor**
##### SUMMARY
fixes https://github.com/ansible/awx/issues/569

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

```
awx: 1.0.1.158
```

### CODE REVIEW

File: awx/ui/client/src/inventories-hosts/inventories/standard-inventory/edit/inventory-edit.controller.js [hunk 1]
```diff
@@ -41,16 +40,14 @@ function InventoriesEdit($scope, $location,
...
-                    field_id: 'inventory_inventory_variables'
-                });
-            }
+        ParseTypeChange({
+            scope: $scope,
+            variable: 'inventory_variables',
+            parse_variable: 'parseType',
+            field_id: 'inventory_inventory_variables'
         });
+        //     }
```
Comment (mabashian) [inline awx/ui/client/src/inventories-hosts/inventories/standard-inventory/edit/inventory-edit.controller.js]: can remove

**Comment by mabashian** [comment]
@jaredevantabor tested out all the cases I could think of and this seems to be working well.  I think the build failed due to some api churn yesterday.  If you rebase I bet we'll get a passing build here and should be good to go.

**Review by mabashian — APPROVED** [review]
