### PR TITLE
Fixes SSO Redirect

### LINKED ISSUE #9115: SSO login redirect override URL is not working
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After upgrading to 16.0.0, SSO Login redirect override URL is no longer working.

"Settings->System->Miscellaneous System settings->Details" correctly shows "Login redirect override URL" setting (for example: /sso/login/saml/?idp=MYIDP), but editing is not possible and users are no longer automatically redirected.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Operating System: any
* Web Browser: any

##### STEPS TO REPRODUCE
1. go to Settings->System->Miscellaneous System settings->Details
2. click on Edit
3. "Login redirect override URL" edit field is missing

##### EXPECTED RESULTS
1. go to Settings->System->Miscellaneous System settings->Details
2. click on Edit
3. enter data for "Login redirect override URL"
4. users automatically redirected to SSO

##### ACTUAL RESULTS
1. it's not possible to add/edit SSO override URL ("Login redirect override URL")
2. users are not redirected to SSO

##### ADDITIONAL INFORMATION

Also, would it be possible, when using SSO, to have SSL (SAML) icon and text dominantly displayed inside the login box? Currently, there is no text and the icon (UserCircleIcon) is too small. For SSO (SAML) users it is difficult to figure out that in order to login one needs to click on that tiny-microscopic-icon.

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
This fixes #9115 by simply checking if there is a redirect url in and then replacing it with the existing url in history, navigating the user to the correct login url.
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
redirect

### CODE REVIEW

**Comment by AlexSCorey** [comment]
recheck

**Comment by tiagodread** [comment]
We are gonna have the https://github.com/ansible/awx/pull/9908 in first

File: awx/ui_next/src/screens/Login/Login.jsx [hunk 1]
```diff
@@ -61,13 +61,16 @@ function AWXLogin({ alt, i18n, isAuthenticated }) {
       const logoSrc = custom_logo
         ? `data:image/jpeg;${custom_logo}`
         : loginLogoSrc;
+      if (login_redirect_override && !isAuthenticated(document.cookie)) {
+        return window.location.replace(login_redirect_override);
```
Comment (jakemcdermott) [inline awx/ui_next/src/screens/Login/Login.jsx]: @AlexSCorey 

I like the simplicity. That said, burying this deep within an async callback (and conditionally changing its return structure) makes me a little uneasy.  To me, it's an unexpected thing to do in an asynchronous api response handler.

We have other conditional redirects further down in the component definition that use the typical `react-router` semantics and, if possible, I think we should do something similar.

I think all you'd need to do is add:

```jsx
  if (login_redirect_override) {
    return <Redirect to={login_redirect_override} />;
  }
```

to [this line](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Login/Login.jsx#L115)

**Review by jakemcdermott — CHANGES_REQUESTED** [review]

File: awx/ui_next/src/screens/Login/Login.jsx (hunk 1 above)
Comment (jakemcdermott) [reply awx/ui_next/src/screens/Login/Login.jsx]: or, if react-router doesn't like external urls:

```jsx
  if (login_redirect_override) {
    window.location.replace(login_redirect_override);
    return null;
  }
```
to [this line](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Login/Login.jsx#L115)

Comment (AlexSCorey) [reply awx/ui_next/src/screens/Login/Login.jsx]: React router does not like redirecting outside of the app.  Using option 1

**Review by jakemcdermott — APPROVED** [review]

**Comment by one-t** [comment]
recheck

**Comment by one-t** [comment]
Hey, @AlexSCorey - once the check failure is fixed I can take a look at this. I'll be out next week so we may need to reassign if I can't get it hammered out

**Comment by one-t** [comment]
I've verified this is working correctly. SSO verification is a manual process currently (though I'd like to automate it in the future).
