### PR TITLE
Fixes translation issue on Schedule Form

### LINKED ISSUE #10973: In ja google-chrome, while editing 'schedule with prompts' schedule, string 'Start date/time' appears partially localized, needs inspection
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When in ja google-chrome, while editing 'Schedule with prompts' schedule, source string 'Start date/time' appears partially localized as '開始 date/time'

### AWX version

19.3.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

_No response_

### Operating system

_No response_

### Web browser

_No response_

### Steps to reproduce

1. Launch UI in ja google-chrome
2. Click 'Templates' from nav bar
3. Click (or create) the said Job Template titled 'Tower4 - new schedule with prompts
4. Click on the 'Schedules' tab
5. Click on the schedule named 'another sched'
6. Click on the 'Edit' button
7. Observe translation of label 'Start date/time'

### Expected results

100% Translated (into Japanese)

### Actual results

Appears partially localized (date/time appears in English)

### Additional information

1. Screenshot 1 highlighting the partially localized string when in ja google-chrome
I18Ni18n-16817_1_Screen_Shot_2021-08-02_at_7 27 14_am-1_2
2. Said source string 'Start date/time' which appears partially localized as '開始 date/time' seems not available at: https://github.com/ansible/awx/blob/devel/awx/ui/src/locales/ja/messages.po 
3. Rather for 'start date/time', only following message is found at: https://github.com/ansible/awx/blob/424dbe82085bec9b2d60c64162f15ff5f938f65a/awx/ui/src/locales/ja/messages.po#L5979-L5980

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
Fixes #10973

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
Screen Shot 2021-08-30 at 3 11 51 PM

### CODE REVIEW

**Comment by tiagodread** [comment]
The string is not showing as translated on Prod or Dev build, I've tried using Zulu

Screenshot from 2021-08-31 10-50-24

File: awx/ui/src/components/Schedule/shared/DateTimePicker.js [hunk 1]
```diff
@@ -33,7 +33,11 @@ function DateTimePicker({ dateFieldName, timeFieldName, label }) {
 
   return (
     <FormGroup
-      fieldId={`schedule-${label}-datetime`}
+      fieldId={
+        dateFieldName.startsWith('start')
```
Comment (nixocio) [inline awx/ui/src/components/Schedule/shared/DateTimePicker.js]: This change relies on the dateFieldName  to always contain `start` or `end` as starting string, but dateFieldName is just a string that can be modified to be any.   Did I misread this change?
```suggestion
        fieldId={`schedule-${label}`}
```

File: awx/ui/src/components/Schedule/shared/DateTimePicker.js [hunk 2]
```diff
@@ -42,19 +46,23 @@ function DateTimePicker({ dateFieldName, timeFieldName, label }) {
           ? 'default'
           : 'error'
       }
-      label={`${label} date/time`}
+      label={`${label}`}
```
Comment (nixocio) [inline awx/ui/src/components/Schedule/shared/DateTimePicker.js]: No need of string interpolation. `label` is already a string.

File: awx/ui/src/components/Schedule/shared/DateTimePicker.js [hunk 3]
```diff
@@ -42,19 +46,23 @@ function DateTimePicker({ dateFieldName, timeFieldName, label }) {
...
     >
       <DateTimeGroup>
         <DatePicker
-          aria-label={t`${label} date`}
+          aria-label={
+            dateFieldName.startsWith('start') ? t`Start date` : t`End date`
```
Comment (nixocio) [inline awx/ui/src/components/Schedule/shared/DateTimePicker.js:51]: Same comment as above about dateFieldName.

File: awx/ui/src/components/Schedule/shared/DateTimePicker.js [hunk 4]
```diff
@@ -42,19 +46,23 @@ function DateTimePicker({ dateFieldName, timeFieldName, label }) {
...
           value={dateField.value.split('T')[0]}
           onChange={onDateChange}
         />
         <TimePicker
           placeholder="hh:mm AM/PM"
           stepMinutes={15}
-          aria-label={t`${label} time`}
+          aria-label={
+            dateFieldName.startsWith('start') ? t`Start time` : t`End time`
+          }
```
Comment (nixocio) [inline awx/ui/src/components/Schedule/shared/DateTimePicker.js:62]: Same comment as above about dateFieldName.

**Review by nixocio — CHANGES_REQUESTED** [review]

File: awx/ui/src/components/Schedule/shared/DateTimePicker.js (hunk 1 above)
Comment (AlexSCorey) [reply awx/ui/src/components/Schedule/shared/DateTimePicker.js]: I initially implemented this change in order to get the tests to pass, however, I will revert this change and introduce a dataCy prop that we can use as a selector for our unit tests.

File: awx/ui/src/components/Schedule/shared/DateTimePicker.js (hunk 3 above)
Comment (AlexSCorey) [reply awx/ui/src/components/Schedule/shared/DateTimePicker.js:51]: It is a string, that could possibly change, but then the form won't work because that string is the same name as the values key.  I am unable to simply grab the key off of formik and use that in the `DateTimePicker` because there are cases where there are 2 of the components on the screen at the same time that manipulate Start date/time and End date/time of the form. Instead, I'll pass the name of the field into `<DateTimePicker>` based on the appropriate component name (End date/time vs Start date/time).  This way, if the field name changes in formik it'll still work.

**Review by nixocio — APPROVED** [review]

**Review by akus062381 — APPROVED** [review]
