### PR TITLE
Prevents API error on node deprovision request

### LINKED ISSUE #12847: fail to put node in deprovisioning state when removing from UI
in feature-mesh-scaling feature branch 
when attempting to remove instance via the UI i get a 301 error 

```
POST /api/v2/instances/3 HTTP/1.1
Host: awx-feature-mesh-scaling.apps.hao-demo.testing.ansible.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
X-CSRFToken: <omitted>
Content-Length: 31
Origin: https://awx-feature-mesh-scaling.apps.hao-demo.testing.ansible.com/
DNT: 1
Connection: keep-alive
Referer: https://awx-feature-mesh-scaling.apps.hao-demo.testing.ansible.com/
Cookie: <omitted>
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
```

```
{"node_state":"deprovisioning"}
```

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
resolves #12847 

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - UI

### CODE REVIEW

File: awx/ui/src/screens/Instances/Shared/RemoveInstanceButton.js [hunk 1]
```diff
@@ -79,13 +79,13 @@ function RemoveInstanceButton({ itemsToRemove, onRemove, isK8s }) {
 
   const isDisabled =
     itemsToRemove.length === 0 || itemsToRemove.some(cannotRemove);
-
+  console.log(itemsToRemove, removeDetails);
```
Comment (kialam) [inline awx/ui/src/screens/Instances/Shared/RemoveInstanceButton.js]: Remove console.log here.

**Review by kialam — CHANGES_REQUESTED** [review]
This returns a `405` since `POST` is not a supported option. We need to change the request to a `PATCH` request instead.

Also, the unit tests should be removed since they're using Enzyme and not RTL.
Screen Shot 2022-09-09 at 9 50 55 AM

File: awx/ui/src/setupProxy.js [hunk 2]
```diff
@@ -1,13 +1,16 @@
 const { createProxyMiddleware } = require('http-proxy-middleware');
 
-const TARGET = process.env.TARGET || 'https://localhost:8043';
+const TARGET =
```
Comment (kialam) [inline awx/ui/src/setupProxy.js]: We should remove this file from being committed.

File: awx/ui/src/screens/Instances/InstancePeers/InstancePeerList.test.js [hunk 3]
```diff
@@ -0,0 +1,188 @@
+import React from 'react';
```
Comment (kialam) [inline awx/ui/src/screens/Instances/InstancePeers/InstancePeerList.test.js]: These tests files should be removed.

**Review by kialam — APPROVED** [review]
This is good to merge once test files and setupProxy.js has been removed. There is a bug where the Instances page does not refresh/fetch the new list of Instances once a user has deprovisioned the Instance but that can be addressed in a separate PR.
